// console.log('Hello World');
// let firtsName= "Rohit";
// console.log(firtsName);
// const interestRate=0.3;
// interestRate=1;
// console.log(interestRate);
let name="Rohit";
let age=21;
let isApproved=false;
let firstName=undefined;
let lastName =null;
console.log(lastName);
